### ISSUE TITLE
pydicom pip install workaround?

### ISSUE THREAD

**Issue by aribesik** [pieper/dicomsort#22]
Hi there, not super familiar with python - there were some issues installing pydicom with conda on our system, so I tried installing pydicom using pip using venv. After activating the environment containing pydicom, I tried to run dicomsort.py but it is unable to locate the pydicom module.

How can I setup the path or whatever is necessary for dicomsort.py to know where pydicom can be imported from? Thank you

**Comment by aribesik** [comment]
Traceback (most recent call last):
  File "dicomsort.py", line 31, in <module>
    import dicom
ModuleNotFoundError: No module named 'dicom'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dicomsort.py", line 34, in <module>
    import pydicom
ModuleNotFoundError: No module named 'pydicom'

**Comment by aribesik** [comment]
nevermind... lol. figured it out - had to change the venv's pyvenv.cfg file so that include-system-site-packages is set to true - works now!
